/**
 * Bloom Metabolics. Blog Post Management.
 * Reads MDX frontmatter for blog index and routing.
 */

export interface Post {
  slug: string
  title: string
  description: string
  author: string
  published_at: string
  updated_at?: string
  category: string
  tags: string[]
  reading_time: number
  draft: boolean
}

const POSTS: Post[] = [
  // ─── PUBLISHED ────────────────────────────────────────────────────────
  {
    slug: 'mens-sexual-health',
    title: "Men's Sexual Health: Causes of Low Testosterone, ED & Low Libido",
    description: 'Learn the causes of erectile dysfunction, low testosterone, and low libido in men. Discover symptoms, treatments, and when to seek medical care.',
    author: 'Bloom Metabolics Clinical Team',
    published_at: '2026-06-17',
    category: 'TRT',
    tags: ['mens-health', 'sexual-health', 'erectile-dysfunction', 'low-testosterone', 'libido', 'ed', 'hormone-optimization', 'trt'],
    reading_time: 9,
    draft: false,
  },
  {
    slug: 'tesamorelin-benefits',
    title: 'Tesamorelin Benefits: Fat Loss, Growth Hormone Support & Healthy Aging',
    description: 'Learn how Tesamorelin works, its potential benefits for visceral fat reduction, body composition, recovery, and longevity, plus the science behind this growth hormone peptide.',
    author: 'Bloom Metabolics Clinical Team',
    published_at: '2026-06-17',
    category: 'Peptides',
    tags: ['tesamorelin', 'peptide therapy', 'growth hormone', 'ghrh', 'visceral fat', 'body composition', 'healthy aging', 'longevity'],
    reading_time: 8,
    draft: false,
  },
  {
    slug: 'glutathione-benefits',
    title: 'Glutathione Benefits: Energy, Detoxification, Skin Health & Healthy Aging',
    description: 'Learn how glutathione supports detoxification, immune health, skin wellness, recovery, and healthy aging. Discover the science behind the body’s master antioxidant.',
    author: 'Bloom Metabolics Clinical Team',
    published_at: '2026-06-17',
    category: 'Longevity',
    tags: ['glutathione', 'antioxidant', 'detoxification', 'longevity', 'healthy aging', 'skin health', 'immune support', 'oxidative stress'],
    reading_time: 8,
    draft: false,
  },
  {
    slug: 'ghk-cu-vs-botox',
    title: 'GHK-Cu vs. Botox: Can the Beauty Peptide Improve Skin Quality Naturally?',
    description: 'Can GHK-Cu replace Botox? Learn how the copper peptide supports collagen, skin elasticity, wound healing, and hair growth — and how it differs from Botox at a cellular level.',
    author: 'Bloom Metabolics Clinical Team',
    published_at: '2026-06-09',
    category: 'Peptides',
    tags: ['ghk-cu', 'copper peptides', 'peptide therapy', 'anti-aging', 'skincare', 'botox alternative', 'hair growth', 'collagen'],
    reading_time: 8,
    draft: false,
  },
  {
    slug: 'real-benefits-of-trt',
    title: 'The Real Benefits of Testosterone Replacement Therapy (TRT)',
    description: 'Learn the real benefits of Testosterone Replacement Therapy (TRT), including improved energy, muscle growth, libido, mental clarity, and body composition. Explore TRT risks, side effects, and safety.',
    author: 'Bloom Metabolics Clinical Team',
    published_at: '2026-06-04',
    category: 'TRT',
    tags: ['trt', 'testosterone', 'hormone-optimization', 'mens-health', 'libido', 'muscle-growth'],
    reading_time: 9,
    draft: false,
  },
  {
    slug: 'what-is-retatrutide',
    title: 'What Is Retatrutide (Reta)?',
    description: 'Learn what retatrutide (Reta) is, how it works, and how it compares to semaglutide and tirzepatide for weight loss. Explore the latest clinical trial results, potential benefits, common side effects, risks, and FDA approval status of this next-generation obesity medication.',
    author: 'Bloom Metabolics Clinical Team',
    published_at: '2026-06-04',
    category: 'GLP-1',
    tags: ['retatrutide', 'glp-1', 'weight-loss', 'tirzepatide', 'semaglutide', 'obesity'],
    reading_time: 10,
    draft: false,
  },
  {
    slug: 'what-is-trt',
    title: 'What Is TRT? A Complete Guide to Testosterone Replacement Therapy',
    description: 'Testosterone replacement therapy explained: what it is, how it works, who it\'s for, and what to expect from physician-supervised TRT protocols.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-05-13',
    updated_at: '2026-05-13',
    category: 'TRT',
    tags: ['trt', 'testosterone', 'hormone therapy', 'mens health'],
    reading_time: 15,
    draft: false,
  },
  {
    slug: 'low-testosterone-symptoms',
    title: '12 Signs of Low Testosterone Most Men Miss',
    description: 'The clinical signs of low testosterone go beyond low libido. Learn the 12 symptoms most men overlook, and when to get tested.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-05-13',
    updated_at: '2026-05-13',
    category: 'TRT',
    tags: ['low testosterone', 'symptoms', 'mens health', 'hormone imbalance'],
    reading_time: 10,
    draft: false,
  },
  {
    slug: 'compounded-glp1-explained',
    title: 'Compounded GLP-1 Medications: What Patients Should Know',
    description: 'Understanding compounded semaglutide and tirzepatide: how they differ from brand-name medications, FDA regulatory status, and what to look for in a provider.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-05-13',
    updated_at: '2026-05-13',
    category: 'GLP-1',
    tags: ['glp-1', 'compounded', 'semaglutide', 'tirzepatide', 'fda'],
    reading_time: 12,
    draft: false,
  },

  // ─── DRAFTS: TRT ─────────────────────────────────────────────────────
  {
    slug: 'trt-benefits-timeline',
    title: 'TRT Benefits Timeline: What to Expect and When',
    description: 'A week-by-week and month-by-month timeline of what men commonly experience after starting testosterone replacement therapy.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'testosterone', 'results', 'timeline'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'trt-side-effects',
    title: 'TRT Side Effects: What the Evidence Actually Shows',
    description: 'An evidence-based review of testosterone replacement therapy side effects, risk factors, and how monitoring protocols mitigate them.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'side effects', 'safety', 'testosterone'],
    reading_time: 12,
    draft: true,
  },
  {
    slug: 'trt-blood-work',
    title: 'TRT Blood Work: The Complete Lab Panel Guide',
    description: 'Every marker your TRT lab panel should include, what the results mean, and how your physician uses them to optimize your protocol.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'blood work', 'labs', 'testosterone'],
    reading_time: 12,
    draft: true,
  },
  {
    slug: 'trt-dosing-protocols',
    title: 'TRT Dosing Protocols: Frequency, Amounts, and Optimization',
    description: 'How TRT dosing is determined, why frequency matters, and how physicians adjust protocols based on lab response.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'dosing', 'protocol', 'testosterone'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'testosterone-injections-guide',
    title: 'Testosterone Injections: A Patient Guide to Self-Administration',
    description: 'Step-by-step guide to self-administering testosterone injections: subcutaneous and intramuscular techniques, supplies, and best practices.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'injections', 'self-administration', 'guide'],
    reading_time: 8,
    draft: true,
  },
  {
    slug: 'hcg-and-trt',
    title: 'HCG and TRT: Fertility Preservation and Testicular Function',
    description: 'How HCG works alongside testosterone replacement therapy to support fertility, testicular volume, and intratesticular testosterone production.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'hcg', 'fertility', 'testosterone'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'trt-body-composition',
    title: 'TRT and Body Composition: What the Research Supports',
    description: 'How testosterone replacement therapy may influence muscle mass, fat distribution, and metabolic rate: and what it cannot do alone.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'body composition', 'muscle', 'fat loss'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'trt-cost-guide',
    title: 'How Much Does TRT Cost? A Transparent Pricing Guide',
    description: 'What testosterone replacement therapy costs through online clinics, insurance considerations, and what your membership should include.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'cost', 'pricing', 'insurance'],
    reading_time: 8,
    draft: true,
  },
  {
    slug: 'online-trt-clinic',
    title: 'How to Choose an Online TRT Clinic',
    description: 'What to look for: and what to avoid, when selecting an online testosterone replacement therapy provider.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'TRT',
    tags: ['trt', 'telehealth', 'online clinic', 'provider'],
    reading_time: 10,
    draft: true,
  },

  // ─── DRAFTS: GLP-1 ───────────────────────────────────────────────────
  {
    slug: 'what-are-glp1-medications',
    title: 'What Are GLP-1 Medications? A Complete Patient Guide',
    description: 'How GLP-1 receptor agonists work, what they are prescribed for, and what patients should understand before starting therapy.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'semaglutide', 'tirzepatide', 'weight management'],
    reading_time: 12,
    draft: true,
  },
  {
    slug: 'semaglutide-vs-tirzepatide',
    title: 'Semaglutide vs Tirzepatide: Comparing GLP-1 Medications',
    description: 'A clinical comparison of semaglutide and tirzepatide: mechanisms, efficacy data, side effect profiles, and how physicians choose between them.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'semaglutide', 'tirzepatide', 'comparison'],
    reading_time: 12,
    draft: true,
  },
  {
    slug: 'glp1-side-effects',
    title: 'GLP-1 Side Effects: What to Expect During Treatment',
    description: 'Common and uncommon side effects of GLP-1 receptor agonists, management strategies, and when to contact your provider.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'side effects', 'semaglutide', 'tirzepatide'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'glp1-metabolic-health',
    title: 'GLP-1 Medications and Metabolic Health Beyond Weight Loss',
    description: 'Emerging research on GLP-1 receptor agonists and their potential effects on cardiovascular, hepatic, and metabolic markers.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'metabolic health', 'cardiovascular', 'research'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'glp1-dosing-titration',
    title: 'GLP-1 Dosing and Titration: How Physicians Manage Your Protocol',
    description: 'Why GLP-1 medications require gradual dose titration, standard schedules, and how your provider adjusts based on response.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'dosing', 'titration', 'protocol'],
    reading_time: 8,
    draft: true,
  },
  {
    slug: 'glp1-injection-guide',
    title: 'GLP-1 Injection Guide: Self-Administration for Patients',
    description: 'A step-by-step guide to self-administering subcutaneous GLP-1 injections: technique, supplies, timing, and storage.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'injections', 'self-administration', 'guide'],
    reading_time: 6,
    draft: true,
  },
  {
    slug: 'glp1-exercise-nutrition',
    title: 'Exercise and Nutrition on GLP-1 Therapy',
    description: 'How to structure training and nutrition to preserve lean mass, support metabolic health, and optimize outcomes during GLP-1 treatment.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'exercise', 'nutrition', 'body composition'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'medical-weight-loss-cost',
    title: 'Medical Weight Loss Cost: What Patients Should Expect to Pay',
    description: 'A transparent breakdown of medical weight loss costs: GLP-1 medications, consultations, monitoring, and what affects pricing.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'cost', 'pricing', 'weight loss'],
    reading_time: 8,
    draft: true,
  },
  {
    slug: 'online-glp1-telehealth',
    title: 'Online GLP-1 Prescribing: What to Look for in a Telehealth Provider',
    description: 'How to evaluate online GLP-1 clinics: physician oversight, pharmacy quality, monitoring standards, and red flags to avoid.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'telehealth', 'online clinic', 'provider'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'glp1-maintenance-strategy',
    title: 'GLP-1 Maintenance Strategy: What Happens After You Reach Your Goal',
    description: 'Transitioning from active weight loss to maintenance on GLP-1 therapy: dose adjustments, lifestyle factors, and long-term planning.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-06-01',
    category: 'GLP-1',
    tags: ['glp-1', 'maintenance', 'weight management', 'long-term'],
    reading_time: 10,
    draft: true,
  },

  // ─── DRAFTS: PEPTIDES ────────────────────────────────────────────────
  {
    slug: 'what-is-peptide-therapy',
    title: 'What Is Peptide Therapy? A Clinical Overview',
    description: 'An introduction to therapeutic peptides: what they are, how they work, current clinical applications, and what the evidence supports.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-07-01',
    category: 'Peptides',
    tags: ['peptides', 'peptide therapy', 'regenerative medicine'],
    reading_time: 12,
    draft: true,
  },
  {
    slug: 'bpc157-research',
    title: 'BPC-157: Current Research and Clinical Considerations',
    description: 'A review of BPC-157 research: mechanism of action, preclinical data, clinical potential, and what patients should understand.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-07-01',
    category: 'Peptides',
    tags: ['peptides', 'bpc-157', 'recovery', 'research'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'tb500-research',
    title: 'TB-500 (Thymosin Beta-4): Research Overview and Clinical Context',
    description: 'What the current research says about TB-500: tissue repair mechanisms, preclinical evidence, and the gap between research and clinical use.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-07-01',
    category: 'Peptides',
    tags: ['peptides', 'tb-500', 'thymosin beta-4', 'recovery'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'nad-plus-longevity',
    title: 'NAD+: The Essential Molecule for Energy, Longevity, and Cellular Health',
    description: 'NAD+ is one of the most studied molecules in longevity science. Learn how it supports energy production, DNA repair, sirtuin activation, cognitive function, and metabolic health — and why levels decline with age.',
    author: 'Bloom Metabolics Clinical Team',
    published_at: '2026-06-09',
    category: 'Longevity',
    tags: ['nad+', 'longevity', 'anti-aging', 'mitochondria', 'sirtuins', 'dna repair', 'cellular health', 'metabolic health'],
    reading_time: 9,
    draft: false,
  },
  {
    slug: 'peptide-compounding-fda',
    title: 'Peptide Compounding and FDA Regulation: What Patients Need to Know',
    description: 'Understanding the regulatory landscape for compounded peptides: FDA category classifications, pharmacy standards, and patient safety.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-07-01',
    category: 'Peptides',
    tags: ['peptides', 'fda', 'compounding', 'regulation'],
    reading_time: 10,
    draft: true,
  },
  {
    slug: 'growth-hormone-peptides',
    title: 'Growth Hormone Peptides: Mechanisms, Research, and Clinical Use',
    description: 'An overview of growth hormone-releasing peptides and secretagogues: how they work, what the research shows, and clinical considerations.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-07-01',
    category: 'Peptides',
    tags: ['peptides', 'growth hormone', 'ghrp', 'secretagogues'],
    reading_time: 12,
    draft: true,
  },
  {
    slug: 'peptide-safety-quality',
    title: 'Peptide Safety and Quality: How to Evaluate Sources and Products',
    description: 'Quality indicators for compounded peptides: COA requirements, pharmacy standards, purity testing, and red flags to avoid.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-07-01',
    category: 'Peptides',
    tags: ['peptides', 'safety', 'quality', 'compounding'],
    reading_time: 8,
    draft: true,
  },
  {
    slug: 'peptide-therapy-future',
    title: 'The Future of Peptide Therapy: Emerging Research and Clinical Directions',
    description: 'Where peptide therapy is headed: novel compounds in clinical trials, regulatory developments, and the evolving evidence base.',
    author: 'Brian DeGuzman, RN',
    published_at: '2026-07-01',
    category: 'Peptides',
    tags: ['peptides', 'research', 'clinical trials', 'future'],
    reading_time: 10,
    draft: true,
  },
]

export function getAllPosts(includeDrafts = false): Post[] {
  const posts = includeDrafts ? POSTS : POSTS.filter(p => !p.draft)
  return posts.sort((a, b) => b.published_at.localeCompare(a.published_at))
}

export function getPostBySlug(slug: string): Post | null {
  return POSTS.find(p => p.slug === slug) || null
}

export function getPostsByCategory(category: string): Post[] {
  return POSTS.filter(p => p.category === category && !p.draft)
}

export function getRelatedPosts(post: Post, limit = 3): Post[] {
  return POSTS.filter(p => p.slug !== post.slug && !p.draft && p.tags.some(t => post.tags.includes(t))).slice(0, limit)
}
