// next-env.d.ts (auto-generated by Next.js) declares these via
// `/// <reference types="next/image-types/global" />`, but our tsconfig's
// include[] doesn't pull that file in, so its module declarations aren't
// visible. Re-declaring locally lets static image imports type-check and
// gives next/image its StaticImageData (width/height + blurDataURL).
declare module '*.png' {
  const src: import('next/image').StaticImageData
  export default src
}
declare module '*.jpg' {
  const src: import('next/image').StaticImageData
  export default src
}
declare module '*.jpeg' {
  const src: import('next/image').StaticImageData
  export default src
}
declare module '*.webp' {
  const src: import('next/image').StaticImageData
  export default src
}
declare module '*.avif' {
  const src: import('next/image').StaticImageData
  export default src
}
