'use client'

// California AB 3030 — GenAI disclosure on clinical communications
import { useState } from 'react'
import { Bot, Check } from 'lucide-react'

interface AIDisclosureProps {
  variant: 'clinical' | 'administrative'
  contentId?: string
  onHumanReview?: (data: { reviewerId: string; reviewedAt: string; contentHash: string }) => void
}

export default function AIDisclosure({ variant, contentId, onHumanReview }: AIDisclosureProps) {
  const [reviewed, setReviewed] = useState(false)

  function handleReview() {
    setReviewed(true)
    onHumanReview?.({
      reviewerId: 'current_user', // resolved at call site
      reviewedAt: new Date().toISOString(),
      contentHash: contentId || '',
    })
  }

  if (variant === 'administrative') {
    return (
      <span className="inline-flex items-center gap-1 text-[10px] text-[#8a8268] italic">
        <Bot className="w-3 h-3" /> System-generated
      </span>
    )
  }

  // Clinical variant — full AB 3030 disclosure
  if (reviewed) {
    return (
      <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-emerald-500/5 border border-emerald-500/10">
        <Check className="w-3 h-3 text-emerald-400" />
        <span className="text-[10px] text-emerald-400">Human-reviewed by clinician</span>
      </div>
    )
  }

  return (
    <div className="px-3 py-2 rounded-lg bg-amber-500/5 border border-amber-500/10">
      <div className="flex items-center gap-2 mb-1">
        <Bot className="w-3 h-3 text-amber-400" />
        <span className="text-[10px] text-amber-400 font-medium">AI-Generated Content</span>
      </div>
      <p className="text-[10px] text-[#8a8268] leading-relaxed">
        This content was generated by an AI system and has not been reviewed by a human clinician. To reach a human team member, contact brian@bloommetabolics.com.
      </p>
      <button
        onClick={handleReview}
        className="mt-1.5 text-[10px] text-amber-400 hover:text-amber-300 underline transition-colors"
      >
        Mark as Human-Reviewed
      </button>
    </div>
  )
}
